config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'



  #get 's_page/home'
  root 's_page#home'
  resources :users do
     member do
        get :followers, :following
     end
  end
  get '/search', to: 'songs#search'
  get '/usearch', to: 'users#search'
  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  resources :accont_activations, only: [:edit]
  resources :songs, only: [:new, :create, :destroy, :show, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
 
  resources :messages, only: [:create, :index, :new]
  get '/deactivated', to: 'users#deactivate'
  resources :conversations do
    resources :messages
  end
  get '/category', to: 'songs#categories'
  get '/cat', to: 'songs#cat_add'
  get '/tags', to: 'tags#tags'
  get '/like', to: 'songs#like'
  get '/usercats', to: 'users#usercats'
  post '/usercats', to: 'users#add_cat'
  #post "photos", to: "comments#create"

  # get 'users/edit'
  # patch 'users/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # match ':controller(/:action(/:id(.:format))', via: :get
end

app/models/user.rb
class User < ApplicationRecord
    has_many :songs, dependent: :destroy
    has_many :usercats
    #For Delete All User Posts With His Or Her
    has_many :active_relationships, class_name:   "Relationship",
                                    foreign_key:  "follower_id",
                                    dependent: :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "followed_id",
                                     dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    # which explicitly tells Rails that the source of the following array is the set of followed ids.
    has_many :followers, through: :passive_relationships, source: :follower
    
    has_many :comments, through: :songs, dependent: :destroy
    # has_many :comments, through: :songs
    has_many :sender, class_name: "User",
                       foreign_key: "sender_id",
                       dependent: :destroy
    has_many :conversations, foreign_key: :sender_id
    has_many :recipient, class_name: "User",
                       foreign_key: "recipient_id",
                       dependent: :destroy
    has_many :likes
    # has_many :sender, through: :sender, source: :sender
    # has_many :reciver, through: :reciver, source: :reciver
    attr_accessor :remember_token, :reset_token, :activation_token
    before_save {self.name = name.downcase}
    before_create(:create_activation_digest)
    validates(:name, presence: true, length: {maximum: 50},
                                     uniqueness: {case_sensetive: true})
    VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates(:email, presence: true, length: {maximum: 250},
                                      format: {with: VALIDATE_EMAIL_REGEX},
                                      uniqueness: {case_sensetive: true})
    has_secure_password
    validates(:password, presence: true, length: {minimum: 5},
                                          allow_nil: true)
    #Login Form Methods
       def User.digest(str)
          cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
          BCrypt::Password.create(str, cost: cost)
       end
       def User.new_token
          SecureRandom.urlsafe_base64
       end

    def remember
        self.remember_token = User.new_token
        update_attribute(:login_digest, User.digest(remember_token))
    end

    def forget
        update_attribute(:login_digest, nil)
    end

    def authenticated?(field, login_token)
         digest = send("#{field}_digest")
         return false if digest.nil?
         BCrypt::Password.new(digest).is_password?(login_token)
    end
    def send_activation_email
         UserMailer.accont_activation(self).deliver_now
    end

    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
    def activate
        # update_attribute(:activated, true)
        # update_attribute(:activated_at, Time.zone.now) 
        update_columns(activated: true, activated_at: Time.zone.now) 
    end
    
    def create_reset_digest
       self.reset_token = User.new_token
    #    User.reset_digest = User.digest(reset_token)
       update_columns(reset_digest: User.digest(reset_token), reset_send_at: Time.zone.now)
    end

    def send_reset_digest
       UserMailer.password_reset(self).deliver_now
    end
    
    def reset_token_expired?
       User.reset_send_at < 2.hours.ago
    end

    def feed
       Song.where("user_id IN (:following_ids) OR user_id = :user_id", following_ids: following_ids, user_id: id)
       #Can Be Dont Add self
#        following_ids = "SELECT followed_id FROM relationships
#        WHERE  follower_id = :user_id"
#        Song.where("user_id IN (#{following_ids})
#        OR user_id = :user_id", user_id: id)
    end
    #Follow art
    def follow(other_user)
       following << other_user
    end
    def unfollow(other_user)
       following.delete(other_user)
    end
    def following?(other_user)
       following.include?(other_user)
    end
    scope :find_user, -> (str) do
       where("name LIKE ?", "%#{str}%") 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action(:logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers])
    before_action(:corrent_user, only: [:edit, :update])
    before_action(:is_admin, only: [:destroy])
    #Top Lines Run Before Actions And Its ggod for user validation for valid user
    def index
        @users = User.paginate(page: params[:page])
     # @users = User.all
    end 
    def new
       @user = User.new    
    end
    def create
       @user = User.new(user_params)
       if @user.save
          @user.send_activation_email
          flash[:info] = "Accont Created!"
          redirect_to root_url   
       elsif
          render new_user_path
       end
    end
    def show
       @user = User.find(params[:id])
       @songs = @user.songs.paginate(page: params[:page])
       #for find user by id you cant use find_by method
    end
    def edit
       @user = User.find(params[:id])
    end
    def update
       @user = User.find(params[:id])
       if(@user.update_attributes(edit_params)) then
           flash[:info] = "Updated"
           redirect_to @user
       else
           render 'edit'
       end
    end
    def delete
    
    end
    def deactivate
       @usere = User.find(params[:id])
       @usere.update_attribute(:activated, false)
    end
    def destroy
         User.find(params[:id]).destroy
         flash[:success] = "User Deleted"
         redirect_to users_url
    end
    def following
       @title = "Following"
       @user = User.find(params[:id])
       @users = @user.following.paginate(page: params[:page])
       render 'show_follow'
    end
    def followers
       @title = "Followers"
       @user = User.find(params[:id])
       @users = @user.followers.paginate(page: params[:page])
       render 'show_follow'
    end
    def search
       @user_find = User.find_user(params[:q])
    end
    def usercats
        @cats = Category.all    
    end
    def add_cat
       @cats = params[:pop]
    #    @cats.each do |cat|
          Category.find_by("name = ? ", @cats)
    #    end
    end
    private
    def usercat_params
       params.permit(cat_ids: [])
    end
    def corrent_user
       @user  = User.find(params[:id])
       redirect_to(user_path) unless @user == current_user
    end
    def is_admin
        redirect_to root_url unless current_user.admin?
    end
    def user_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def edit_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(email, size = 80)
     hashed_id = Digest::MD5.hexdigest(email)
     url = "https://secure.gravatar.com/avatar/#{hashed_id}?s=#{size}"
     image_tag(url, alt: "picture", class: "img rounded-circle") 
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
<%= hidden_field_tag :followed_id, @user.id %>
<%= f.submit "follow", class: 'btn btn-info mrg w-25 p-3' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>   
   <% unless current_user.following?(@user) %>
        <%= render("follow") %>
   <% else %>
        <%= render("unfollow") %>
        <%= link_to "Message", "#", class: 'start-conversation' %>
   <% end %>
<% else %>

<%= link_to :Edit, edit_user_path, class: 'btn btn-success mrg w-25' %>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

                            <div class="form-group input-group">
                                <%= render("shared/error_messages", object: f.object) %>
                                <%= f.label :Name, class: 'label label-info stl mrg', style: 'margin-top: 10px;' %>
                                <%= f.text_field :name, class: 'form-control flt mrg' %>
                            </div>

                            <div class="form-group input-group">
                                <%= f.label :email, class: 'label label-info stl mrg' %>
                                <%= f.email_field :email, class: 'form-control flt mrg' %>
                            </div>

                            <div class="form-group input-group">
                                <%= f.label :password, class: 'label label-info stl mrg' %>
                                <%= f.password_field :password, class: 'form-control flt mrg' %>
                            </div>
                            <div class="form-group input-group">
                                 <%= f.label :Confirm, class: 'label label-info stl mrg' %>
                                 <%= f.password_field :password_confirmation, class: 'form-control flt mrg' %>
                            </div>
                               <%= f.submit yield(:text), class: 'btn btn-info mrg' %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: {method: :delete}) do |f| %>
<%= f.submit "unfollow", class: 'btn btn-danger mrg w-25 p-3' %>
<% end %>

app/views/users/edit.html.erb
<% if current_user.id == @user.id %>
<%= provide(:title, "Edit Profile") %>
<% provide(:text, "Change") %>
<%= form_for(@user) do |f| %>

                            <div class="form-group input-group">
                                <%= render("shared/error_messages", object: f.object) %>
                                <%= f.label :Name, class: 'label label-info stl mrg', style: 'margin-top: 10px;' %>
                                <%= f.text_field :name, class: 'form-control flt mrg' %>
                            </div>

                            <div class="form-group input-group">
                                <%= f.label :email, class: 'label label-info stl mrg' %>
                                <%= f.email_field :email, class: 'form-control flt mrg' %>
                            </div>

                            <div class="form-group input-group">
                                <%= f.label :password, class: 'label label-info stl mrg' %>
                                <%= f.password_field :password, class: 'form-control flt mrg' %>
                            </div>
                            <div class="form-group input-group">
                                 <%= f.label :Confirm, class: 'label label-info stl mrg' %>
                                 <%= f.password_field :password_confirmation, class: 'form-control flt mrg' %>
                            </div>
                            <div class="form-group input-group">
                                 <%= f.label :Bio, class: 'label label-info stl mrg' %>
                                 <%= f.text_area :bio, class: 'form-control flt mrg' %>
                            </div>
                               <%= f.submit yield(:text), class: 'btn btn-info mrg' %>
<% end %>
<% else %>
  <%  %>
<% end %>

app/views/users/index.html.erb
<%= provide(:title, "Home Music System") %>
<% @users.each do |user| %>
 <div class="user_cs">
<%= gravatar_for(user.email.downcase) %>
<span class="label label-info stl2"><%= user.name %></span>
 <% if !user.admin? && current_user.admin? %>
 <%= link_to "", user, method: :delete, data: {confirm: "Delete!"}, class:'btn btn-danger glyphicon glyphicon-trash' %>
 <%= link_to "", edit_song_path(current_user.id), class: 'btn btn-warning glyphicon glyphicon-pencil' %>
 <%= link_to "", "#{deactivated_path}/#{user.id}", class: 'btn btn-primary glyphicon glyphicon-eye-open' %>
 <% end %>
  <%= link_to "", "#", class: 'start-conversation btn btn-success glyphicon glyphicon-envelope', "data-sid" => current_user.id, "data-rip" => user.id %>
 </div>
<% end %>
<%=  will_paginate %>
  <%= react_component 'Users' %>

 

app/views/users/new.html.erb
<%= provide(:title, "SignUp") %>
<%= provide(:text, "SignUp")%>
   <%= render("form") %>
   <% # :password and :password_confirmation is bcrypt has_secure_password 
      # in database is password_digest and in model :password 
      # this both convert to password_digest in database and  
    %>

app/views/users/search.html.erb
<%  @user_find.each do |userd| %>
<%= userd.name %>
<br/>
<% end %>

app/views/users/show.html.erb
<%= provide(:title, "Personal Page") %>
<div><%= gravatar_for(@user.email.downcase) %></div>
Username: <div class="label label-default fs"><%= @user.name  %></div>
<br/>
E-mail: <div class="label label-default fs"><%= @user.email %></div>
<% if logged_in? && current_user.id == @user.id then %>
<%= link_to "Edit", edit_user_path, class: 'btn btn-info' %>
<%= link_to "+Add", new_song_path, class: 'btn btn-warning' %>
<br/>
<%= link_to " Category", usercats_path, class: 'btn btn-primary glyphicon glyphicon-plus' %>
<br/>
<% end %>
<%= render('shared/stats') %>
<br/>
<%= render('follow_form') if logged_in? %>
<br/>
<br/>
    <div class="panel panel-primary">
      <div class="panel-heading">Bio</div>
      <div class="panel-body"><%= @user.bio %></div>
    </div>


<br/>
<% if @songs.any? then %>
<div class="panel panel-default">
  <div class="panel-body">
  <span class="label label-info mrg uln">Songs: <%= @user.songs.count %></span>
  </div>
</div>
   <br/>
   <hr>
   <%= render(@songs) %>
   <%= will_paginate @songs %>
<% end %>
<br/>
<% @user.comments.each do |comment| %>
<%= comment.content %> ||| <%=  comment.user_id %> ||| <%= comment.song_id %>
<br/>
<% end %>

app/views/users/show_follow.html.erb
<%= provide(:title, @title) %>
<%= gravatar_for(@user.email.downcase, 80) %>
<%= @user.name %>
<br/>
<br/>
<table class="table table-bordered table-dark lft">

<% @users.each do |user| %>
<tr>
<td> <%= gravatar_for user.email.downcase, 30 %></td>
<td> <%= link_to user.name, user %></td>
<td><%= user.email %></td>
</tr>
<% end %>

</table>
<br/>
<% if @users.any? then %>

<% end %>

app/views/users/usercats.html.erb
<%= form_for usercats_path, :html => {:multipart => true} do |f| %>
    <% Category.all.each do |cat| %>
        <%= check_box_tag cat.name, cat.id %>
    <% end %>                     
<%= f.submit :Add, class: 'btn btn-success glyphicon glyphicon-plus' %>
<% end %>