config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'



  #get 's_page/home'
  root 's_page#home'
  resources :users do
     member do
        get :followers, :following
     end
  end
  get '/search', to: 'songs#search'
  get '/usearch', to: 'users#search'
  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  resources :accont_activations, only: [:edit]
  resources :songs, only: [:new, :create, :destroy, :show, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
 
  resources :messages, only: [:create, :index, :new]
  get '/deactivated', to: 'users#deactivate'
  resources :conversations do
    resources :messages
  end
  get '/category', to: 'songs#categories'
  get '/cat', to: 'songs#cat_add'
  get '/tags', to: 'tags#tags'
  get '/like', to: 'songs#like'
  get '/usercats', to: 'users#usercats'
  post '/usercats', to: 'users#add_cat'
  #post "photos", to: "comments#create"

  # get 'users/edit'
  # patch 'users/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # match ':controller(/:action(/:id(.:format))', via: :get
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :tags
  has_many :liker, class_name: "Like", foreign_key: "user_id"
  has_many :like, through: :liker, source: :liked

  has_many :comments, dependent: :destroy
  default_scope -> {order(id: :desc)}
  mount_uploader :file, VoiceUploader
  mount_uploader :picture, PictureUploader
  validates(:user_id, presence: true)
  validates(:content, presence: true, length: {maximum: 200})
  # validates(:file, presence: true)
  validate(:song_size)
  def self.like?(song)
     like.include?(song)
  end
  def song_size
     if file.size > 10.megabyte then
        errors.add(:file, "File Cant Be More Than 10MB")
     end
  end
  def Song.search(string)
     if string then
        Song.where("content LIKE ? ", string) 
     end

  end
  def Song.like
    #  update_attribute(like: Song.like + 1)  
  end
  scope :find_query, -> (str) do
    where("(content LIKE ?) OR (file LIKE ?)", "%#{str}%", "%#{str}%")
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    
    include ActionController::Live
    before_action(:logged_in_user, only: [:create, :edit, :destroy])
    before_action(:corrent_user, only: [:destroy])
    def new
       @song = Song.new
       @cats = Category.all
    end
    def create
      @song = current_user.songs.build(song_params)
      @category = Category.find_by(name: params[:category])
      @song.category_id = @category.id
      if @song.save then
          @tags = params[:tags].split(', ')
          @tags.each do |tag|
             @song.tags.create!(name: tag)
          end
          flash[:success] = "Music Uploaded"
          redirect_to current_user
      else
          flash[:danger] = "Error"
          render('new')
      end
    end

    def show
       
       @song = Song.find(params[:id])
       current_song(@song.id)
       @tags = Tag.where("song_id = ?", @song.id)
       @user = User.find(@song.user_id)
       @comment = Comment.new
       @comments = @song.comments.paginate(page: params[:page])
       
       response.headers['Content-Type'] = 'text/event-stream'
       @song.each do |line|
          response.stream.write line.lyrics
          sleep line.num_beats
       end
       ensure
          response.stream.close
    end
  def edit

  end
  def destroy
      @song.destroy
      flash[:success] = "Post Deleted"
      redirect_to(request.referrer || root_url)
  end
  
  # def search
  #   # terms = params[:s].splite(' ')
  #   @some_song = Song.search(params[:s])
  #   render 'search'
  # end
  def search
    @songs_find = Song.find_query(params[:s])
    render 'search'
  end
  def categories
      @categories = Category.all
      render 'categories'
  end
  def cat_add
    if params[:pop] == 1 then
       @cats = params[:pop]
       Relation.create!(category_id = 1)
    end
  end
  def like
     @like = Like.new(user_id: current_user.id, song_id: params[:sid])
     if @like.save then
         flash[:success] = "Liked"
         redirect_to request.referrer
     else
         redirect_to request.referrer
     end
  end
  private
  def song_params
     params.require(:song).permit(:content, :file, :picture)
  end
  def corrent_user
    @song = current_user.songs.find_by(id: params[:id])
    redirect_to root_url unless @song
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_song.html.erb
<br/>
<span class= "form-margin"><%= link_to gravatar_for(song.user.email, 40), song.user %><span>>
<%= link_to song.user.name, song_path(song.id) %>
<% if current_user == @user then %>
<%= link_to "", song, method: :delete, data: {confirm: "Are You Sure"}, class: 'btn btn-danger glyphicon glyphicon-trash' %>
<%= link_to("", edit_song_path(song.id) , class: 'btn btn-warning glyphicon glyphicon-pencil') %>
<% end %>
<br/>




<span class="form-margin"><%= image_tag song.picture.url if song.picture? %></span>
<br/>
<br/>

<span class="form-margin">
<% if song.file? then %>
<%= audio_tag(song.file.url, controls: true) %>
<% end %>
</span>
<br/>

<span class="form-margin label label-warning">Posted : </span><%= time_ago_in_words(song.created_at) %> Ago
<br/>
<% if song.like? then %>
<%= link_to "", "#{like_path}/?sid=#{song.id}", class: 'glyphicon glyphicon-heart' %>
<% end %>
<br/>
<span class="form-margin well"><%= song.content %></span>
<br/>

app/views/songs/categories.html.erb
<% @categories.each do |category| %>
<% @cats = Array.new %>
<% @cats << category.name %>
<% end %>
<script>


</script>

<%= form_for cat_path do |f| %>
<%= f.check_box @categories[0].name %><%= @categories[0].name %>
<br/>
<%= f.check_box @categories[1].name %><%= @categories[1].name %>
<br/>
<%= f.check_box @categories[2].name %><%= @categories[2].name %>
<br/>
<%= f.check_box @categories[3].name %><%= @categories[3].name %>
<br/>
<%= f.check_box @categories[4].name %><%= @categories[4].name %>
<br/>
<%= f.check_box @categories[5].name %><%= @categories[5].name %>
<br/>
<% end  %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/new.html.erb
<%= provide(:title, "New Music") %>
<% if logged_in? then %>
<%= form_for(@song, class: 'form-group') do |f| %>
<%= render("shared/error_messages", object: f.object) %>
<%= f.label :Caption, class: 'label label-info' %>
<%= f.text_area :content, class: 'form-control' %>
<%= f.label :File, class: 'label label-info' %>
<%= f.file_field :file, class: 'file' %>
<%= f.label :Picture, class: 'label label-info' %>
<%= f.file_field :picture, class: 'file' %>
<%= select_tag :category, options_for_select(@cats.collect {|cat| [cat.name]}), :prompt => "Select", class: 'form-control', id: 'sel1' %>
<br/>
<%= text_area_tag :tags, placeholder: 'Your tags' %>
<%= f.submit "Add", class: 'btn btn-info' %>
<% end %>
<% else %>
<%= render("session/new") %>
<% end %>

app/views/songs/search.html.erb
<% @songs_find.each do |song| %>
<%= song.id %> ::
<%= song.content  %>
<br/>
<% if song.picture.url then %>
<%= image_tag(song.picture.url, class: 'form-margin') %>
<%= audio_tag song.file.url, controls: true, class: 'form-margin' %>
<% end %>
<% end %>

app/views/songs/show.html.erb
<% current_song(@song.id) %>
<%= gravatar_for(@user.email.downcase, 80) %>
<%= link_to @user.name, user_path(@song.user_id) %>
<br/>
<% if @song.picture.present? then %>
<%= image_tag @song.picture.url , class: 'form-margin' %>
<br/>
<%= audio_tag @song.file.url, controls: true, class: 'form-margin' %>
<% end %>
<%= @text %><br/>
<br/>
<button class=" btn btn-warning glyphicon glyphicon-heart-empty" onClick=""></button>
<%= @song.like if @song.like %>
<span class="form-margin label label-warning">Posted : </span><%= time_ago_in_words(@song.created_at) %> Ago
<br/>
Name Song: <%= @song.content %><br/>
<% @tags.each do |tag|  %>
<span class="badge">#<%= link_to tag.name, "#{tags_path}?tag=#{tag.name}" %></span>
<% end %>
<br/>
<%= render 'comments/comment_form' %>
<br/>
<br/>
<%= render @comments %>