config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'



  #get 's_page/home'
  root 's_page#home'
  resources :users do
     member do
        get :followers, :following
     end
  end
  get '/search', to: 'songs#search'
  get '/usearch', to: 'users#search'
  get '/signup', to: 'users#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  resources :accont_activations, only: [:edit]
  resources :songs, only: [:new, :create, :destroy, :show, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]
 
  resources :messages, only: [:create, :index, :new]
  get '/deactivated', to: 'users#deactivate'
  resources :conversations do
    resources :messages
  end
  get '/category', to: 'songs#categories'
  get '/cat', to: 'songs#cat_add'
  get '/tags', to: 'tags#tags'
  get '/like', to: 'songs#like'
  get '/usercats', to: 'users#usercats'
  post '/usercats', to: 'users#add_cat'
  #post "photos", to: "comments#create"

  # get 'users/edit'
  # patch 'users/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # match ':controller(/:action(/:id(.:format))', via: :get
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Navbar", root_path, class: 'navbar-brand cl' %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent myNavbar">
    <ul class="nav navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Home", users_path, class: 'nav-link cl' %>
      </li>
      <li class="nav-item">
        <a class="nav-link cl" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle cl" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled cl" href="#">Disabled</a>
      </li>
      <% if logged_in? then %>
      <li><%= link_to "Logout", logout_path, class: 'cl' %></li>
      <% else %>
      <li>
          <%= link_to "Sign Up", signup_path, class: 'cl' %>
      </li>
      <li>
      	<%= link_to "Login", login_path, class: 'cl' %>
      </li>
      <% end %>
    </ul>
    <div>
      <%= form_tag("/usearch", method: "get", class: 'form-inline mt') do %>
           <%= text_field_tag :q, "", class: 'form-control', placeholder: "Find user" %>
           <%= submit_tag :Users, class: 'btn btn-success glyphicon glyphicon-search' %>
      <% end %>
    </div>
    <%= form_tag("/search", method: "get", class: 'form-inline mt') do %>
          <%= text_field_tag :s, "", class: 'form-control', placeholder: "Find Anything" %>
          <%= submit_tag :Search, class: 'btn btn-info' %>
    <% end %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<% if logged_in? then %>
<div class="sidebar">
  <%= link_to "Profile", current_user, class: 'btn btn-block btn-info'%>
  <%= link_to "Users", users_path, class: 'btn btn-block btn-info'%>
  <%= link_to "MyPage", users_path, class: 'btn btn-block btn-info'%>
  <%= link_to "Home", root_path, class: 'btn btn-block btn-info'%>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
    <%= render('layouts/header') %>
    
  <aside>
   <pre> <%= render('layouts/sidebar') %></pre>
  </aside>
  <section>
  <div id="container">
  <%= flash.each do |type, msg| %>
      <div class="alert alert-<%= type %>"><%= msg %></div>
  <% end %>
  <div class="react-test"></div>
  <div id ="content"><%= yield %><div> 
  <br/>
  <%= debug(params) if Rails.env.development? %> 
  </div>
  </section>
  </body>
</html>